ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PRACTICE_FINISHED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PRACTICE_ABSENCE';

ALTER TABLE "schedule_occurrences" ADD COLUMN "finishedAt" TIMESTAMP(3);
